/**
 * The world the cards live in.
 *
 * The rules were always a mage's game — you spend mana, you call people onto the field, you
 * draw circles that change what the field means — so the pool is skinned to match without a
 * single rule changing:
 *
 *   - Lands are 魔法石, cut stones that tap for mana.
 *   - Artifacts are 秘寶, the implements a caster hands out: 杖 for power, 環 for speed,
 *     護符 for defence, 鏡 for sight, 冠 for command.
 *   - Enchantments are circles drawn on the world: 領域 covers the whole field, 法陣 marks
 *     one target, 結界 keeps something out.
 *   - Spells are named for what they do and nothing else. No rank prefixes, no 術 or 咒
 *     tacked on the end, no punctuation in the middle — a spell called 熔岩崩落 does not
 *     read better for being called 大熔岩崩落.
 *
 * Creatures are people first. The board is meant to fill up with casters, knights, rangers
 * and druids you could draw a portrait of, not with a bestiary — so the swarms and the
 * beasts that were only ever a body and a number are now characters, and every colour has
 * both 精靈 and 法師 of its own. One subtype each: a card that says 德魯伊 is a druid, and
 * saying 精靈・德魯伊 only makes the type line longer.
 *
 * A tribe is not flavour when a rule names it. `anthem.tribe` and the `callTribe` house
 * effect match by exact string, so `LORE_TRIBES` moves those in the same pass, and the test
 * suite checks that every tribe a rule names is one some creature actually wears.
 */

/** Card id → the single subtype it wears. */
export const LORE_SUBS: Record<string, string[]> = {
  // ── 白：光的教團 ─────────────────────────────────────────────────────────────
  w_acolyte: ['法師'],
  w_lightbringer: ['法師'],
  w_arbiter: ['法師'],
  w_dawn_seer: ['法師'],
  w_hound: ['精靈'],
  w_griffin_scout: ['遊俠'],
  w_falconer: ['遊俠'],
  knight: ['騎士'],
  w_squire: ['騎士'],
  w_ward_knight: ['騎士'],
  hx_twin_blade: ['騎士'],
  w_sunspear_lancer: ['騎士'],
  sunshield: ['騎士'],
  w_paladin: ['騎士'],
  w_crusader: ['騎士'],
  w_oath_keeper: ['騎士'],
  gold_sun_champion: ['騎士'],
  w_healer: ['牧師'],
  w_cleric: ['牧師'],
  w_battle_priest: ['牧師'],
  w_purifier: ['牧師'],
  w_high_cleric: ['牧師'],
  gold_dusk_confessor: ['牧師'],
  w_sentry: ['衛兵'],
  w_shieldwall: ['衛兵'],
  w_temple_guard: ['衛兵'],
  w_banner_squire: ['衛兵'],
  w_lightforge_captain: ['衛兵'],
  angel: ['天使'],
  w_angel_guard: ['天使'],
  w_angel_host: ['天使'],
  w_dove_flock: ['天使'],
  w_seraph_scout: ['天使'],
  w_archangel: ['天使'],
  gold_sky_marshal: ['天使'],
  w_bulwark_titan: ['魔像'],

  // ── 藍：學院 ─────────────────────────────────────────────────────────────────
  u_channel_spirit: ['法師'],
  u_scholar: ['法師'],
  u_illusionist: ['法師'],
  u_archivist: ['法師'],
  u_conjurer: ['法師'],
  u_glimmer_eel: ['法師'],
  tidal_seer: ['法師'],
  u_seer: ['法師'],
  u_oracle_of_tides: ['法師'],
  u_shoal_trickster: ['法師'],
  gold_mind_reaver: ['法師'],
  u_wisp: ['精靈'],
  u_moon_sprite: ['精靈'],
  u_wave_skimmer: ['精靈'],
  gold_storm_djinn: ['精靈'],
  u_tide_shaman: ['薩滿'],
  u_typhoon_caller: ['薩滿'],
  u_current_rider: ['人魚'],
  u_phantom_scout: ['盜賊'],
  u_mist_stalker: ['盜賊'],
  u_depth_guardian: ['衛兵'],
  u_frost_warden: ['衛兵'],
  ray: ['幽靈'],
  u_mind_render: ['幽靈'],
  u_mind_sovereign: ['幽靈'],
  u_riftwing: ['幽靈'],
  u_thoughtweaver: ['幽靈'],
  u_leyline_thief: ['幽靈'],
  u_mnemonic_wraith: ['幽靈'],
  u_ghost_armada: ['幽靈'],
  u_wind_drake: ['龍'],
  u_storm_drake: ['龍'],

  // ── 黑：被埋葬的學院 ─────────────────────────────────────────────────────────
  b_wraith_whelp: ['法師'],
  b_cursed_priest: ['法師'],
  b_death_priest: ['法師'],
  b_venom_spider: ['法師'],
  b_lich_king: ['巫妖'],
  b_bat_swarm: ['精靈'],
  b_soul_siphon_imp: ['精靈'],
  b_rat_swarm: ['盜賊'],
  phantom_assassin: ['盜賊'],
  b_grave_robber: ['盜賊'],
  b_night_blade: ['盜賊'],
  b_swamp_stalker: ['盜賊'],
  b_death_knight: ['騎士'],
  ghoul: ['殭屍'],
  grave_warden: ['殭屍'],
  b_plague_bearer: ['殭屍'],
  b_crypt_guard: ['殭屍'],
  b_zombie_horde_leader: ['殭屍'],
  b_wight_guard: ['殭屍'],
  b_vault_scavenger: ['殭屍'],
  b_grave_titan_whelp: ['殭屍'],
  b_skeleton_archer: ['骷髏'],
  shadow_ward: ['幽靈'],
  b_shade: ['幽靈'],
  b_soul_harvester: ['幽靈'],
  b_gloom_stalker: ['幽靈'],
  b_carrion_bat: ['幽靈'],
  vamp: ['吸血鬼'],
  devourer: ['惡魔'],
  b_soul_flayer: ['惡魔'],
  b_plague_lord: ['惡魔'],
  b_abyssal_horror: ['惡魔'],
  b_reaper_of_souls: ['惡魔'],
  b_bloodpact_fiend: ['惡魔'],
  gold_blood_reaver: ['惡魔'],

  // ── 紅：熔爐與山 ─────────────────────────────────────────────────────────────
  imp: ['法師'],
  r_flame_juggler: ['法師'],
  r_torch_bearer: ['法師'],
  r_ember_sprite: ['精靈'],
  r_volcano_shaman: ['薩滿'],
  dancer: ['狂戰士'],
  berserker_unbound: ['狂戰士'],
  r_firebrand: ['狂戰士'],
  r_marauder: ['狂戰士'],
  r_war_drummer: ['狂戰士'],
  r_berserk_champion: ['狂戰士'],
  r_war_chanter: ['狂戰士'],
  r_axe_fanatic: ['狂戰士'],
  hx_scarred_berserker: ['狂戰士'],
  r_cinder_wolf: ['狂戰士'],
  r_charhound: ['狂戰士'],
  r_forge_hound: ['狂戰士'],
  r_pit_fighter: ['矮人'],
  r_dragon_rider: ['矮人'],
  raider: ['哥布林'],
  chief: ['哥布林'],
  r_goblin_sapper: ['哥布林'],
  r_goblin_scrapper: ['哥布林'],
  drakeling: ['龍'],
  dragon: ['龍'],
  ambush_wyrm: ['龍'],
  r_young_wyrm: ['龍'],
  r_flame_drake: ['龍'],
  r_dragon_whelp: ['龍'],
  r_inferno_wyrm: ['龍'],
  r_elder_dragon: ['龍'],
  r_scale_herald: ['龍'],
  r_hoard_dragon: ['龍'],
  r_flame_giant: ['巨人'],
  r_ashen_titan: ['巨人'],

  // ── 綠：森林 ─────────────────────────────────────────────────────────────────
  g_druid_apprentice: ['法師'],
  g_wild_growth_sprite: ['法師'],
  vine: ['德魯伊'],
  thornmaiden: ['精靈'],
  g_vine_weaver: ['德魯伊'],
  g_thornling: ['精靈'],
  g_root_shaman: ['薩滿'],
  gold_rot_shaman: ['薩滿'],
  g_forest_scout: ['遊俠'],
  g_beetle_swarm: ['遊俠'],
  g_stag_beetle: ['遊俠'],
  g_canopy_serpent: ['遊俠'],
  g_giant_spider: ['遊俠'],
  gold_verdant_paladin: ['騎士'],
  g_verdant_hydra: ['精靈'],
  guardianoak: ['樹人'],
  mendingtreant: ['樹人'],
  g_rootwalker: ['樹人'],
  g_world_tree_avatar: ['樹人'],
  g_bloom_warden: ['樹人'],
  g_thorn_elemental: ['元素'],
  g_vine_horror: ['元素'],
  g_thorn_colossus: ['元素'],
  g_moss_troll: ['巨人'],
  wolf: ['巨狼'],
  g_pack_leader: ['巨狼'],
  g_hunting_wolf_pack: ['巨狼'],
  behemoth: ['魔獸'],
  g_trample_beast: ['魔獸'],
  g_regal_stag: ['魔獸'],
  gold_tide_hydra: ['魔獸'],
  gold_wild_flame: ['魔獸'],

  // ── 無色：被造之物 ───────────────────────────────────────────────────────────
  hx_forge_golem: ['魔像'],
  c_assembly_core: ['魔像'],
  c_overseer: ['魔像'],
  c_forge_wright: ['魔像'],
  c_scrap_servitor: ['傀儡'],
  c_spinner: ['傀儡'],
  c_arc_drone: ['傀儡'],
  c_scrap_hauler: ['傀儡'],
  c_shield_drone: ['傀儡'],
  c_iron_sentinel: ['活鎧'],
  c_siege_engine: ['活鎧'],
  c_iron_bulwark: ['活鎧'],
  c_sentinel_prime: ['活鎧'],
  c_relic_colossus: ['泰坦'],
  c_forge_titan: ['泰坦'],

  // ── 新登場的人物 ─────────────────────────────────────────────────────────────
  x_dawn_scribe: ['法師'],
  x_shield_maiden: ['騎士'],
  x_lantern_saint: ['牧師'],
  x_rune_reader: ['法師'],
  x_mirror_twin: ['精靈'],
  x_tide_archmage: ['法師'],
  x_ash_witch: ['法師'],
  x_grave_courtier: ['吸血鬼'],
  x_bone_marshal: ['骷髏'],
  x_spark_apprentice: ['法師'],
  x_ember_dancer: ['精靈'],
  x_forge_marshal: ['矮人'],
  x_seed_speaker: ['法師'],
  x_thorn_ranger: ['遊俠'],
  x_grove_elder: ['德魯伊'],

  // ── 曲線頂端 ─────────────────────────────────────────────────────────────────
  x_dawn_sovereign: ['天使'],
  x_judgment_seraph: ['天使'],
  x_dawn_titan: ['天使'],
  x_deep_sovereign: ['人魚'],
  x_storm_leviathan: ['海獸'],
  x_dream_architect: ['法師'],
  x_grave_sovereign: ['巫妖'],
  x_soul_tyrant: ['惡魔'],
  x_night_eternal: ['惡魔'],
  x_flame_sovereign: ['巨人'],
  x_magma_titan: ['巨人'],
  x_worldfire_wyrm: ['龍'],
  x_forest_sovereign: ['精靈'],
  x_ancient_ent: ['樹人'],
  x_gaia_avatar: ['元素'],
  x_void_colossus: ['泰坦'],
  x_dawnflame_champion: ['騎士'],

  // ── 衍生物 ───────────────────────────────────────────────────────────────────
  tok_soldier: ['衛兵'],
  tok_goblin: ['哥布林'],
  tok_zombie: ['殭屍'],
  tok_spirit: ['幽靈'],
  tok_wolf: ['巨狼'],
  tok_construct: ['傀儡'],
  tok_thopter: ['傀儡'],
};

/**
 * Tribes named by a rule rather than by flavour, and what they now point at.
 *
 * These have to move in step with `LORE_SUBS` or the anthem quietly stops buffing anything.
 */
export const LORE_TRIBES: Record<string, string> = {
  兵俑: '衛兵',
  狼: '巨狼',
};

/** Card id → its name in the new world. */
export const LORE_NAMES: Record<string, string> = {
  // ── 魔法石：單色是元素本身，雙色與三色各有自己的名字 ────────────────────────
  pln: '光之石',
  isl: '海之石',
  swp: '暗之石',
  mtn: '火之石',
  fst: '木之石',
  wastes: '虛之石',
  skyshoal: '曦潮之石',
  graveglow: '燭骨之石',
  sunforge: '熾陽之石',
  dawn: '晨林之石',
  dusk: '幽淵之石',
  stormvault: '雷弧之石',
  tidegrove: '潮蔓之石',
  emberdeep: '燼血之石',
  rotwood: '腐苔之石',
  wildforge: '焰木之石',
  tri_wub: '冥律之石',
  tri_wur: '霆庭之石',
  tri_wug: '曦澤之石',
  tri_wbr: '血誓之石',
  tri_wbg: '枯榮之石',
  tri_wrg: '荒野之石',
  tri_ubr: '暗湧之石',
  tri_ubg: '潮蝕之石',
  tri_urg: '風暴之石',
  tri_brg: '焦土之石',

  // ── 秘寶：杖(力) 環(速) 護符(守) 鏡(視) 冠(統率) ────────────────────────────
  warhammer: '巨力之杖',
  blessedblade: '曦光之杖',
  c_null_rod: '靜滯之杖',
  c_pulse_cannon: '轟雷之杖',
  r_flame_axe: '焚炎之環',
  c_arc_lance: '弧光之環',
  u_mind_circlet: '心靈之環',
  g_bark_armor: '根紋護符',
  w_aegis_shield: '護誓護符',
  b_bone_ward: '枯骨護符',
  u_scrying_orb: '預視之鏡',
  w_holy_banner: '聖印之冠',

  // ── 結界：領域(全場) 法陣(單體) 結界(阻絕) ──────────────────────────────────
  seal: '輝耀領域',
  w_martyrs_cause: '殉道領域',
  w_oath_of_dawn: '破曉領域',
  r_berserkers_charm: '狂戰領域',
  u_abyssal_chart: '深淵領域',
  w_binding_light: '縛光法陣',
  w_vow_of_duty: '誓約法陣',
  g_verdant_bond: '蒼翠法陣',
  b_shroud_of_night: '凋朽法陣',
  w_sanctuary: '庇護結界',
  hx_aegis_field: '壁障結界',
  bramblewarden: '荊冠結界',
  u_veil_of_secrets: '隱匿結界',

  // ── 法術：只寫它做什麼，不加階位、不加標點 ──────────────────────────────────
  recall: '深淵召還',
  b_dread_summons: '亡者召集',
  c_data_cache: '記憶迴廊',
  g_wild_regrowth: '荒野復甦',
  r_goblin_rally: '哥布林集結',
  r_meteor_shower: '隕石驟雨',
  u_grand_forgetting: '遺忘之潮',
  hx_knight_muster: '騎士召集',
  w_mass_muster: '全境徵召',
  w_final_blessing: '終焉祝福',
  lava: '熔岩崩落',
  c_purge_protocol: '淨除之光',
  u_deep_analysis: '深潮解析',
  hx_unmaking: '萬物解離',
  r_wildfire: '野火蔓延',
  u_grand_illusion: '宏大幻象',
  w_holy_verdict: '聖裁宣告',
  mindrend: '心智撕裂',
  b_soul_shatter: '靈魂震碎',
  b_soul_exchange: '靈魂交換',
  mind_sieve: '記憶蝕刻',
  g_regrowth_ritual: '繁茂儀典',
  b_reap: '靈魂收割',
  b_animate_dead: '死者甦生',
  b_dark_study: '闇識鑽研',
  bone_horde: '白骨召集',
  c_salvage: '殘骸回收',
  c_thopter_foundry: '撲翼構築',
  c_foundry_call: '熔爐召構',
  growth: '自然滋長',
  g_natures_blessing: '自然祝福',
  g_savage_fight: '野性激鬥',
  g_wolfcall: '群狼召集',
  hx_ember_rain: '餘燼之雨',
  goblin_horde: '哥布林召喚',
  farsight_ritual: '預知儀式',
  u_mind_sieve_lesser: '記憶淺蝕',
  hx_seek_sorcery: '秘典檢索',
  muster: '衛兵召集',
  hx_seek_enchant: '法陣共鳴',
  w_healing_light: '治癒之光',
  w_conscript: '民兵召集',
  w_spirit_choir: '靈魂詠唱',
  g_deep_roots: '深根之力',
  u_farsight: '遠見之眼',
  u_tide_surge: '潮湧之力',

  // ── 生物：人物優先，一費多半是還在學的施法者 ────────────────────────────────
  u_channel_spirit: '見習魔法師',
  w_acolyte: '見習聖光師',
  imp: '見習火術師',
  b_wraith_whelp: '見習死靈師',
  g_druid_apprentice: '森語魔法師',
  vine: '見習德魯伊',
  thornmaiden: '荊環精靈',
  g_thornling: '荊藤精靈',
  w_hound: '曦光精靈',
  u_wisp: '風語精靈',
  b_bat_swarm: '噬血精靈',
  r_firebrand: '烙印狂戰士',
  w_sentry: '城牆衛兵',
  b_rat_swarm: '淬毒刺客',
  u_glimmer_eel: '微光術士',
  b_venom_spider: '毒牙巫女',
  b_swamp_stalker: '沼影潛行者',
  b_carrion_bat: '腐羽哨兵',
  b_soul_siphon_imp: '攝魂精靈',
  r_cinder_wolf: '燼火劍士',
  r_charhound: '炭刃鬥士',
  r_forge_hound: '鍛爐劍士',
  r_pit_fighter: '鬥技場矮人',
  g_beetle_swarm: '蟲鳴遊俠',
  g_stag_beetle: '銳角遊俠',
  g_canopy_serpent: '樹冠遊俠',
  g_giant_spider: '結網遊俠',
  g_wild_growth_sprite: '繁生魔法師',
  w_griffin_scout: '馭鷲遊俠',
  w_falconer: '鷲羽遊俠',
  w_dove_flock: '羽翼傳令',
  u_depth_guardian: '深淵守望者',
  u_frost_warden: '霜牢衛兵',
  g_verdant_hydra: '精靈女王',
  u_phantom_scout: '幻影潛行者',
  b_grave_titan_whelp: '墓園巨屍',

  // ── 衍生物 ───────────────────────────────────────────────────────────────────
  tok_soldier: '衛兵衍生物',
};

/**
 * Rules text that names a token or a tribe, and so has to move with them.
 *
 * Exact substring swaps applied to every card's `text`, which is safe because these are
 * token and tribe names — they never appear as part of another word.
 */
export const LORE_TEXT: [string, string][] = [
  ['兵俑衍生物', '衛兵衍生物'],
  ['你操控的兵俑', '你操控的衛兵'],
  ['你操控的其他狼', '你操控的其他巨狼'],
  ['你操控的狼', '你操控的巨狼'],
];
